# Generated by Django 4.1.1 on 2022-11-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('P.P', 'Permiso Especial'), ('T.I', 'Tarjeta de Identidad'), ('R.C', 'Registro Civil'), ('Otro', 'Otro Tipo de Documento')], default='T.I', max_length=6, verbose_name='Tipo de Documento')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('fechaNacimiento', models.DateField(help_text='MM/DD/AAAA', verbose_name='fecha de nacimiento')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('contrasena', models.CharField(max_length=60, verbose_name='Contraseña')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(choices=[('R.C', 'Registro Civil'), ('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('T.I', 'Tarjeta de Identidad'), ('Otro', 'Otro Tipo de Documento')], default='T.I', max_length=5, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=20, verbose_name='Número de Documento')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('fechaNacimiento', models.DateField(help_text='MM/DD/AAAA', verbose_name='fecha de nacimiento')),
                ('edad', models.SmallIntegerField(verbose_name='Edad')),
                ('genero', models.CharField(max_length=60, verbose_name='Género')),
                ('direccionResidencia', models.CharField(max_length=70, verbose_name='Dirección Residencia')),
                ('celularEstudiante', models.CharField(max_length=20, verbose_name='Celular Estudiante')),
                ('colegio', models.CharField(max_length=100, verbose_name='Colegio Anterior Cuidad')),
                ('nombreC_E', models.CharField(max_length=100, verbose_name='Nombre Celular Emergencia')),
                ('nombreAcudiente', models.CharField(max_length=60, verbose_name='Nombre Acudiente')),
                ('numeroC_A', models.CharField(max_length=20, verbose_name='Número Celular Acudiente')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.usuario', verbose_name='Usuario')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.grado', verbose_name='Grado')),
            ],
        ),
    ]
