# Generated by Django 4.1.1 on 2022-11-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AñoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(max_length=10, verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateTimeField(max_length=10, verbose_name='Fecha Fin')),
                ('nombre', models.SmallIntegerField(verbose_name='Nombre Del Año Lectivo')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboPension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesPagago', models.CharField(max_length=2, verbose_name='Mes Pagado')),
                ('valorP_M', models.CharField(max_length=20, verbose_name='Valor Pensión Mensual')),
                ('fechaP_R_P', models.DateTimeField(max_length=10, verbose_name='Fecha De Pago De Recibo Pensión')),
                ('fechaE_R', models.DateTimeField(max_length=10, verbose_name='Fecha De Emisión De Recibo')),
                ('numeroPension', models.SmallIntegerField(verbose_name='Número Pensión')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=20, verbose_name='Valor de Matrícula por Año')),
                ('fechaMatricula', models.DateTimeField(max_length=10, verbose_name='Fecha de Matrícula')),
                ('fechaP_M', models.DateTimeField(max_length=10, verbose_name='Fecha de Pago de Matrícula')),
                ('anioLectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.añolectivo', verbose_name='Año Lectivo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PazySalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=30, verbose_name='Total Cancelado Por Año')),
                ('fecha', models.DateTimeField(max_length=10, verbose_name='Fecha de Generación paz y salvo')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('estadoEstudiante', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado Estudiante')),
                ('ReciboPension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.recibopension', verbose_name='Recibo Pensión')),
            ],
        ),
    ]
