# Generated by Django 4.1.1 on 2022-11-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibopension',
            old_name='mesPagago',
            new_name='mesPagado',
        ),
    ]
