# Generated by Django 4.1.1 on 2022-11-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_rename_mespagago_recibopension_mespagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pazysalvo',
            name='estadoEstudiante',
        ),
    ]
